### ISSUE TITLE
[Feat] 연간/월간 배당금 조회 api를 포트폴리오 기반 조회 api로 변경

### ISSUE THREAD

**Issue by chominho96** [Nexters/payout-server#90]
## 💡 개요
기존의 연간/월간 배당금 조회 api를 포트폴리오 기반으로 동작 방식을 변경합니다.

## 🤩 기능 설명
기존의 ticker-share 기반으로 연간/월간 배당금을 조회하는 방식에서 포트폴리오 분석 시 고유한 UUID를 가지는 포트폴리오를 생성하고, 해당 포트폴리오를 기반으로 정보를 반환하도록 변경합니다.

## 🍒 세부 기능

어떤 세부 기능을 구현할지 말씀해주세요.

- [x] 연간 배당금 조회 api 수정
- [x] 월간 배당금 조회 api 수정

## 📖 참고 사항
클라이언트 개발 도중에 서비스가 중단되지 않도록 기존의 api는 유지하고, 새로운 api를 개발하는 방식으로 구현합니다. 이후, 클라이언트와의 연동 완료 후 기존 api를 삭제합니다.

**Comment by songyi00** [comment]
@chominho96 요거 따로 API 요청 바꾸는 이유가 있을까요?! 기존 기록을 통해 봐야하는 경우라면 포트폴리오 조회 API를 통해 stock, share 다시 얻고 동일한 API 호출하면 될 것 같아서용

**Comment by chominho96** [comment]
아 제가 이해한 바로는 공유하기를 이용할때 뿐만 아니라 포트폴리오 조회를 하는 순간 포트폴리오 객체를 생성하는 방식으로 바뀌는 것으로 이해했어요!! (처음 배당금 조회 들어가자마자 UUID 생성해서 해당 url로 접근)
그래서 이런 방식으로 바뀌어야 한다고 생각했습니다!!

**Comment by songyi00** [comment]
@chominho96 흠 그렇게 될 경우 만약 포트폴리오 저장 기간이 만료되면 조회가 불가능하지 않나욥?
저는 기존 로직대로 동작하고 만약 새로고침 또는 공유 기능을 사용하는 경우 해당 UUID를 사용해서 프론트엔드에서 해당 이력을 다시 조회하는 것을 생각했어요!! 프론트엔드와 추가 논의가 필요한 상황일까요? 🤔

**Comment by chominho96** [comment]
포트폴리오 저장 기간이 만료되면 조회가 불가능하다고 하신 부분이 헷갈리는데 어차피 공유하기 버튼을 눌렀을 때 UUID가 생성된다고 해도 저장기간이 만료되면 조회가 불가능하지 않나요?!?! 뭔가 제가 기획을 잘못 이해한거 같기도 하네요 😮

**Comment by songyi00** [comment]
@chominho96 오호 배당금 조회 API를 UUID 기반으로 바꾸면 반드시 UUID를 통해 조회해야하는거 아닌가욥?? 아님 선택적으로 파라미터를 넣는 방향을 생각하신건가요? 👀

**Comment by chominho96** [comment]
네네 맞아요!! 제가 이해가 잘 안된 부분은 유효기간 만료가 되는 시점인데, 어차피 초기에 포트폴리오를 조회하는 시점에서는 생성된 직후이니까 유효기간이 만료될 것 같진 않고, 다른 사람들에게 공유를 하거나 링크를 저장했을 때 일정 시간 이후 유효기간이 만료되는 것으로 이해해서요!!
그렇게 되면 UUID로 처음부터 조회해도 이전과 동작은 같을거라고 생각했어요..!!

**Comment by songyi00** [comment]
@chominho96 
아 이해했어요!! 그런 방식을 생각하신거군요??
그럼 이 API뿐만 아니라 포트폴리오 조회와 관련된 모든 API(섹터 비중 분석, 종목 상세 조회 등)도 포트폴리오 id 를 기반으로 조회해야할 것 같은데 그럼 전부 포트폴리오 id에 종속된 API들이 될 것 같아서요! 배당금 조회 API만 요청이 바뀌는 이유가 있을까용?

**Comment by songyi00** [comment]
@chominho96 
ㅋㅋㅋㅋ저는 포트폴리오 분석 클릭 -> UUID 생성 -> UUID를 통해 ticker, share 조회 -> 기존 API들 조회(요청 변경 없이)
요 흐름을 생각하긴 했어요! 포트폴리오 id 에 종속된 API들이 될 것 같아서 ticker, share만으로 검색 가능한 API 가 어떤가 싶었슴다 
근데 포트폴리오 조회시 [포트폴리오 UUID 생성]이 반드시 선행조건으로 들어가는 것으로 정한다면 전부 바꾸는 것도 괜찮다고 생각해요!!!

**Comment by chominho96** [comment]
아하 UUID를 통해 ticker, share를 조회하면 어떤 방식으로 되는건가요?? url은 UUID로 이루어지고 일단 db에 저장은 안 하는 방식일까요?!
사실 저도 가능하다면 기존 인터페이스를 유지하면서 가는 방향이 더 괜찮은거 같아서요 ㅋㅋㅋㅋㅋ큐ㅠㅠ

**Comment by songyi00** [comment]
1. 포트폴리오 UUID 생성 API
2. 포트폴리오 UUID 기반 ticker, share 조회 API 
이렇게 2개 만들고 포트폴리오 조회 버튼 클릭시에 FE에서 1번 API 호출해서 그대로 사용하는 방식 말씀드린 거였어요! url자체는 FE에서 저희가 준 UUID 기반으로 생성하고 그 URL 로 접근했을 시 2번 API 호출해서 다시 요청 정보 얻구요!
